In [1425]:
import sys, matplotlib.pyplot as plt, numpy as np, pandas as pd, time, math,random
pd.set_option('display.max_columns',None)
marathon_data=pd.read_csv('c:\\Users\\willi\Downloads\\Project1_data.csv')
marathon_data=marathon_data.dropna()
marathon_data['Time']=pd.to_timedelta(marathon_data['Time'])
marathon_data.Time=marathon_data.Time.apply(lambda x: x.seconds /float(3600))

#marathon_data=marathon_data[marathon_data.Year != 2013]

marathon_data=marathon_data[(marathon_data.Name != 'private') & (marathon_data.Name != 'unknown runner')]
marathon_data=marathon_data[marathon_data.Name.str.contains('#') == False]

data_pivot = pd.pivot_table(marathon_data, index = ["Id"], columns = "Year", values = ["Rank","Age Category", "Time"], aggfunc= "first")

In [1426]:
data_pivot

Rank                                                                    \
Year  2003 2004 2005    2006    2007    2008    2009    2010    2011    2012   
Id                                                                             
1      NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2      NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3      NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4      NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5      NaN  NaN  NaN  2013.0  2002.0  2343.0  2415.0  2455.0  3140.0  3329.0   
6      NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
7      NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
8      NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
9      NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN  1637.0   
10     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
11     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
12     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
13     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
14     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
15     NaN  NaN  NaN     NaN     NaN  2032.0     NaN     NaN  2706.0  2523.0   
16     NaN  NaN  NaN     NaN     NaN     NaN  1654.0  1021.0  1301.0  1196.0   
17     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
18     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
19     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
20     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
21     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
22     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN  1598.0     NaN   
23     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
24     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
25     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
26     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
27     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
28     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
29     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
30     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
...    ...  ...  ...     ...     ...     ...     ...     ...     ...     ...   
30388  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
30389  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
30390  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
30391  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
30392  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
30393  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
30394  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
30395  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
30396  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
30397  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
30398  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
30399  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
30400  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
30401  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
30402  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
30403  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
30404 

In [1427]:
test=data_pivot[pd.notnull(data_pivot['Time',2016])]

In [1428]:
test.tail()

Rank                                                                      \
Year 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015    2016   
Id                                                                              
3006  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1801.0   
3007  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1536.0   
3008  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   502.0   
3009  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  1893.0   
3010  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  2774.0   

     Age Category                                                              \
Year         2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015   
Id                                                                              
3006          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
3007          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
3008          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
3009          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
3010          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

           Time                                                              \
Year  2016 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015   
Id                                                                            
3006  40.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
3007  35.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
3008  35.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
3009  40.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
3010  40.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

                
Year      2016  
Id              
3006  4.667500  
3007  4.469722  
3008  3.703611  
3009  4.736389  
3010  5.798333

In [1429]:
data_pivot=data_pivot[pd.notnull(data_pivot['Time',2016])]

In [1430]:
data_pivot

Rank                                                                    \
Year 2003 2004 2005    2006    2007    2008    2009    2010    2011    2012   
Id                                                                            
1     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5     NaN  NaN  NaN  2013.0  2002.0  2343.0  2415.0  2455.0  3140.0  3329.0   
6     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
7     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
8     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
9     NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN  1637.0   
10    NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
11    NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
12    NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
13    NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
14    NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
15    NaN  NaN  NaN     NaN     NaN  2032.0     NaN     NaN  2706.0  2523.0   
16    NaN  NaN  NaN     NaN     NaN     NaN  1654.0  1021.0  1301.0  1196.0   
17    NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
18    NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
19    NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
20    NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
21    NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
22    NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN  1598.0     NaN   
23    NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
24    NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
25    NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
26    NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
27    NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
28    NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
29    NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
30    NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
...   ...  ...  ...     ...     ...     ...     ...     ...     ...     ...   
2981  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2982  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2983  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2984  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2985  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2986  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2987  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2988  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2989  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2990  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2991  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2992  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2993  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2994  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2995  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2996  NaN  NaN  NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2997  NaN  NaN  NaN     NaN     NaN     NaN     NaN    

In [1431]:
len(data_pivot)

3010

In [1432]:
def create_frame(last_year):
    start = time.time()
    
    #This is the function to create a frame with the relavant features for each runner, given a year
    #The basic process is we create a pandas pivot table to help us, then we iterate over this pivot table (mostly using apply)
    #to create a new pandas dataframe (new_frame) that contains all relavent features 
    
    #the year we input (last_year) is the last year that we look at (1 year back from current)
    #IE, if we are looking to train a model to predict for 2017, we would give 2015 as the last_year, and the features would include all years up to 2015
    #Then, to predict for 2017 we input 2016 to include features
    
    new_frame = pd.DataFrame(data = {"Id": marathon_data.Id, "Sex": marathon_data.Sex})
    new_frame = new_frame.drop_duplicates("Id")
    new_frame["Sex"] = pd.get_dummies(new_frame["Sex"])
    #1 is male, 0 is female
    
    new_frame.index = new_frame.Id
    
    #helper functions
    def lastfilled(row):
        key = last_year
        while pd.isnull(row.loc[key]): 
            key = key-1
            #if (key == 2013):
            #    key = key - 1
            if (key < 2003): 
                return None 
        return (last_year - key + 1)
        
    def valuelast(row):
        key = last_year
        while pd.isnull(row.loc[key]): 
            key = key - 1
            #if (key == 2013):
            #    key = key - 1
            if (key < 2003): 
                return None
        return row.loc[key]
    
    #for i in range(0,(last_year - 2002)):
        #Here we iterate over the relavent columns in order to get the dummies for participation
        #Each column will be a boolean variable, with a 1 if the runner participated that year, and a 0 otherwise
        #the output is expressed in terms of lags: IE, Lag_1 is one year ago, Lag_4 is 4 years ago...
        #new_frame["_".join(("Lag",str(i + 1)))] = pd.isnull(data_pivot["Rank"]).iloc[:,(last_year - 2003 - i)].apply(lambda x: 0 if x else 1)

    new_frame["Num Marathons"] = data_pivot.apply(lambda x: x.iloc[0:(last_year - 2002)].count() , axis = 1)
    #number of marathons ran
    new_frame["Years Since Last"] = data_pivot.apply(lambda x: lastfilled(x["Rank"]), axis = 1)
    #years since last ra 
    new_frame["Time of Last"] = data_pivot.apply(lambda x: valuelast(x["Time"]), axis = 1)
    #time of the last marathon they competed in 
    new_frame["Age Last"] = data_pivot.apply(lambda x: valuelast(x["Age Category"]), axis = 1)
    new_frame['Sex Time']=new_frame['Time of Last']*new_frame['Sex']
    #NOTE: these apply functions are very time-costly. It takes around 60seconds to run this function fully
    #It would be possible to optimize this, but I am not sure if it is worth my time
    
    #Normalization on the time column 
    #new_frame["Time of Last"] = (new_frame["Time of Last"] - new_frame["Time of Last"].min()) / (new_frame["Time of Last"].max() - new_frame["Time of Last"].min())
   
    new_frame["Dummy"] = np.ones(len(new_frame))
    
    del new_frame["Id"]
    
    print(time.time() - start)
    return new_frame

In [1433]:
#Create our dataframe, looking back from 2016
train_df = create_frame(2015)
#remove entries where there are no races
train_df = train_df[train_df["Num Marathons"] > 0 ]
del train_df["Years Since Last"]
#train_df["Dummy"] = np.ones(len(train_df))
train_array = train_df.as_matrix()

7.73799991608


In [1434]:
train_df

Sex  Num Marathons  Time of Last  Age Last  Sex Time  Dummy
Id                                                               
4     0.0            1.0      3.882500      35.0  0.000000    1.0
5     1.0            8.0      5.720556      42.0  5.720556    1.0
7     0.0            1.0      4.078611      42.0  0.000000    1.0
9     0.0            3.0      4.335000      50.0  0.000000    1.0
11    1.0            2.0      5.464722      40.0  5.464722    1.0
15    0.0            4.0      5.461389      40.0  0.000000    1.0
16    0.0            5.0      4.143056      45.0  0.000000    1.0
18    0.0            1.0      4.004167      50.0  0.000000    1.0
22    1.0            1.0      4.287222      44.0  4.287222    1.0
23    1.0            1.0      4.057222      25.0  4.057222    1.0
31    0.0            1.0      3.641667      45.0  0.000000    1.0
32    0.0            1.0      4.342222      36.0  0.000000    1.0
37    0.0            1.0      4.825833      45.0  0.000000    1.0
40    0.0            1.0      1.727778      44.0  0.000000    1.0
41    1.0            1.0      5.090000      37.0  5.090000    1.0
45    0.0            2.0      4.711944      45.0  0.000000    1.0
46    0.0            1.0      4.924444      46.0  0.000000    1.0
50    0.0            1.0      3.704167      35.0  0.000000    1.0
51    0.0            1.0      5.437500      50.0  0.000000    1.0
53    0.0            1.0      6.436944      48.0  0.000000    1.0
55    0.0            1.0      2.826111      39.0  0.000000    1.0
57    0.0            1.0      4.228056      37.0  0.000000    1.0
63    1.0            4.0      4.655000      40.0  4.655000    1.0
64    0.0            1.0      3.893889      44.0  0.000000    1.0
66    1.0            4.0      3.911389      40.0  3.911389    1.0
67    0.0            2.0      4.586667      45.0  0.000000    1.0
68    0.0            5.0      4.543611      45.0  0.000000    1.0
70    0.0            4.0      4.407222      55.0  0.000000    1.0
74    1.0            2.0      4.770833      45.0  4.770833    1.0
87    0.0            1.0      2.043333      18.0  0.000000    1.0
...   ...            ...           ...       ...       ...    ...
2842  0.0            2.0      6.252222      40.0  0.000000    1.0
2858  0.0            2.0      3.626111      40.0  0.000000    1.0
2868  1.0            1.0      1.998333      25.0  1.998333    1.0
2869  1.0            5.0      5.042500      65.0  5.042500    1.0
2873  0.0            4.0      4.229722      45.0  0.000000    1.0
2876  0.0            1.0      4.816389      40.0  0.000000    1.0
2877  0.0            2.0      5.809444      40.0  0.000000    1.0
2882  1.0            3.0      5.097778      50.0  5.097778    1.0
2884  0.0            2.0      3.672500      60.0  0.000000    1.0
2897  0.0            3.0      1.718889      46.0  0.000000    1.0
2898  0.0            7.0      4.420833      35.0  0.000000    1.0
2899  0.0            3.0      3.608889      45.0  0.000000    1.0
2903  0.0            3.0      5.645833      47.0  0.000000    1.0
2911  1.0            4.0      3.872222      35.0  3.872222    1.0
2923  1.0            1.0      3.760833      48.0  3.760833    1.0
2927  1.0            1.0      3.491111      40.0  3.491111    1.0
2928  0.0            1.0      5.208889      33.0  0.000000    1.0
2939  0.0            3.0      3.394722      40.0  0.000000    1.0
2940  0.0            1.0      3.679444      29.0  0.000000    1.0
2945  0.0            2.0      5.066111      45.0  0.000000    1.0
2946  0.0            7.0      4.204722      39.0  0.000000    1.0
2953  1.0            1.0      4.527778      45.0  4.527778    1.0
2957  0.0            2.0      5.221111      32.0  0.000000    1.0
2958  0.0            1.0      3.962222      38.0  0.000000    1.0
2975  0.0            4.0      4.741389      70.0  0.000000    1.0
2978  1.0            4.0      6.642500      55.0  6.642500    1.0
2979  0.0            1.0      4.051389      40.0  0.000000    1.0
2982  0.0            1.0      4.094444      41

In [1435]:
train_array

array([[  0.        ,   1.        ,   3.8825    ,  35.        ,
          0.        ,   1.        ],
       [  1.        ,   8.        ,   5.72055556,  42.        ,
          5.72055556,   1.        ],
       [  0.        ,   1.        ,   4.07861111,  42.        ,
          0.        ,   1.        ],
       ..., 
       [  0.        ,   1.        ,   4.09444444,  41.        ,
          0.        ,   1.        ],
       [  0.        ,   1.        ,   4.78555556,  42.        ,
          0.        ,   1.        ],
       [  1.        ,   1.        ,   4.15638889,  35.        ,
          4.15638889,   1.        ]])

In [1436]:
train_array*train_array

array([[  0.00000000e+00,   1.00000000e+00,   1.50738062e+01,
          1.22500000e+03,   0.00000000e+00,   1.00000000e+00],
       [  1.00000000e+00,   6.40000000e+01,   3.27247559e+01,
          1.76400000e+03,   3.27247559e+01,   1.00000000e+00],
       [  0.00000000e+00,   1.00000000e+00,   1.66350686e+01,
          1.76400000e+03,   0.00000000e+00,   1.00000000e+00],
       ..., 
       [  0.00000000e+00,   1.00000000e+00,   1.67644753e+01,
          1.68100000e+03,   0.00000000e+00,   1.00000000e+00],
       [  0.00000000e+00,   1.00000000e+00,   2.29015420e+01,
          1.76400000e+03,   0.00000000e+00,   1.00000000e+00],
       [  1.00000000e+00,   1.00000000e+00,   1.72755686e+01,
          1.22500000e+03,   1.72755686e+01,   1.00000000e+00]])

In [1437]:
len(train_array*train_array)

793

In [1438]:
len(train_array)

793

In [1439]:
(train_array*train_array).shape

(793L, 6L)

In [1440]:
train_array[0]

array([  0.    ,   1.    ,   3.8825,  35.    ,   0.    ,   1.    ])

In [1441]:
(train_array*train_array).shape

(793L, 6L)

In [1442]:
train_array_2=np.copy(train_array)
train_array_2=np.append(train_array_2,train_array*train_array,axis=1)

In [1443]:
train_array_2.shape

(793L, 12L)

In [1444]:
train_array_2

array([[  0.00000000e+00,   1.00000000e+00,   3.88250000e+00, ...,
          1.22500000e+03,   0.00000000e+00,   1.00000000e+00],
       [  1.00000000e+00,   8.00000000e+00,   5.72055556e+00, ...,
          1.76400000e+03,   3.27247559e+01,   1.00000000e+00],
       [  0.00000000e+00,   1.00000000e+00,   4.07861111e+00, ...,
          1.76400000e+03,   0.00000000e+00,   1.00000000e+00],
       ..., 
       [  0.00000000e+00,   1.00000000e+00,   4.09444444e+00, ...,
          1.68100000e+03,   0.00000000e+00,   1.00000000e+00],
       [  0.00000000e+00,   1.00000000e+00,   4.78555556e+00, ...,
          1.76400000e+03,   0.00000000e+00,   1.00000000e+00],
       [  1.00000000e+00,   1.00000000e+00,   4.15638889e+00, ...,
          1.22500000e+03,   1.72755686e+01,   1.00000000e+00]])

In [1445]:
train_array_2.shape

(793L, 12L)

In [1446]:
train_array_3=np.copy(train_array_2)
train_array_twice=np.append(train_array,train_array,axis=1)
train_array_3=np.append(train_array,train_array_3*train_array_twice,axis=1)

In [1447]:
train_array_3.shape

(793L, 18L)

In [1448]:
train_df

Sex  Num Marathons  Time of Last  Age Last  Sex Time  Dummy
Id                                                               
4     0.0            1.0      3.882500      35.0  0.000000    1.0
5     1.0            8.0      5.720556      42.0  5.720556    1.0
7     0.0            1.0      4.078611      42.0  0.000000    1.0
9     0.0            3.0      4.335000      50.0  0.000000    1.0
11    1.0            2.0      5.464722      40.0  5.464722    1.0
15    0.0            4.0      5.461389      40.0  0.000000    1.0
16    0.0            5.0      4.143056      45.0  0.000000    1.0
18    0.0            1.0      4.004167      50.0  0.000000    1.0
22    1.0            1.0      4.287222      44.0  4.287222    1.0
23    1.0            1.0      4.057222      25.0  4.057222    1.0
31    0.0            1.0      3.641667      45.0  0.000000    1.0
32    0.0            1.0      4.342222      36.0  0.000000    1.0
37    0.0            1.0      4.825833      45.0  0.000000    1.0
40    0.0            1.0      1.727778      44.0  0.000000    1.0
41    1.0            1.0      5.090000      37.0  5.090000    1.0
45    0.0            2.0      4.711944      45.0  0.000000    1.0
46    0.0            1.0      4.924444      46.0  0.000000    1.0
50    0.0            1.0      3.704167      35.0  0.000000    1.0
51    0.0            1.0      5.437500      50.0  0.000000    1.0
53    0.0            1.0      6.436944      48.0  0.000000    1.0
55    0.0            1.0      2.826111      39.0  0.000000    1.0
57    0.0            1.0      4.228056      37.0  0.000000    1.0
63    1.0            4.0      4.655000      40.0  4.655000    1.0
64    0.0            1.0      3.893889      44.0  0.000000    1.0
66    1.0            4.0      3.911389      40.0  3.911389    1.0
67    0.0            2.0      4.586667      45.0  0.000000    1.0
68    0.0            5.0      4.543611      45.0  0.000000    1.0
70    0.0            4.0      4.407222      55.0  0.000000    1.0
74    1.0            2.0      4.770833      45.0  4.770833    1.0
87    0.0            1.0      2.043333      18.0  0.000000    1.0
...   ...            ...           ...       ...       ...    ...
2842  0.0            2.0      6.252222      40.0  0.000000    1.0
2858  0.0            2.0      3.626111      40.0  0.000000    1.0
2868  1.0            1.0      1.998333      25.0  1.998333    1.0
2869  1.0            5.0      5.042500      65.0  5.042500    1.0
2873  0.0            4.0      4.229722      45.0  0.000000    1.0
2876  0.0            1.0      4.816389      40.0  0.000000    1.0
2877  0.0            2.0      5.809444      40.0  0.000000    1.0
2882  1.0            3.0      5.097778      50.0  5.097778    1.0
2884  0.0            2.0      3.672500      60.0  0.000000    1.0
2897  0.0            3.0      1.718889      46.0  0.000000    1.0
2898  0.0            7.0      4.420833      35.0  0.000000    1.0
2899  0.0            3.0      3.608889      45.0  0.000000    1.0
2903  0.0            3.0      5.645833      47.0  0.000000    1.0
2911  1.0            4.0      3.872222      35.0  3.872222    1.0
2923  1.0            1.0      3.760833      48.0  3.760833    1.0
2927  1.0            1.0      3.491111      40.0  3.491111    1.0
2928  0.0            1.0      5.208889      33.0  0.000000    1.0
2939  0.0            3.0      3.394722      40.0  0.000000    1.0
2940  0.0            1.0      3.679444      29.0  0.000000    1.0
2945  0.0            2.0      5.066111      45.0  0.000000    1.0
2946  0.0            7.0      4.204722      39.0  0.000000    1.0
2953  1.0            1.0      4.527778      45.0  4.527778    1.0
2957  0.0            2.0      5.221111      32.0  0.000000    1.0
2958  0.0            1.0      3.962222      38.0  0.000000    1.0
2975  0.0            4.0      4.741389      70.0  0.000000    1.0
2978  1.0            4.0      6.642500      55.0  6.642500    1.0
2979  0.0            1.0      4.051389      40.0  0.000000    1.0
2982  0.0            1.0      4.094444      41

In [1449]:
def get_y(frame,year):
    temp=data_pivot.loc[frame.index,('Time',year)]
    y_vec=temp.as_matrix()
    return np.array([temp]).T
y_vec=get_y(train_df,2016)

In [1450]:
y_vec

array([[ 5.225     ],
       [ 5.47611111],
       [ 3.60083333],
       [ 5.49666667],
       [ 4.86305556],
       [ 5.14694444],
       [ 4.06027778],
       [ 6.81805556],
       [ 4.16222222],
       [ 4.43361111],
       [ 3.51583333],
       [ 6.72055556],
       [ 4.10555556],
       [ 3.48083333],
       [ 4.51833333],
       [ 4.5325    ],
       [ 3.68888889],
       [ 3.93888889],
       [ 6.01916667],
       [ 5.505     ],
       [ 2.95416667],
       [ 4.66527778],
       [ 4.245     ],
       [ 3.22222222],
       [ 3.91805556],
       [ 4.32361111],
       [ 3.98166667],
       [ 4.4075    ],
       [ 4.49055556],
       [ 6.29388889],
       [ 2.99138889],
       [ 4.48527778],
       [ 4.81277778],
       [ 3.44472222],
       [ 3.9675    ],
       [ 4.71333333],
       [ 3.78444444],
       [ 4.97027778],
       [ 4.94194444],
       [ 3.915     ],
       [ 4.97666667],
       [ 4.96305556],
       [ 3.90111111],
       [ 4.22388889],
       [ 4.245     ],
       [ 4

In [1451]:
y_vec.shape

(793L, 1L)

In [1504]:
y_vec

array([[ 5.225     ],
       [ 5.47611111],
       [ 3.60083333],
       [ 5.49666667],
       [ 4.86305556],
       [ 5.14694444],
       [ 4.06027778],
       [ 6.81805556],
       [ 4.16222222],
       [ 4.43361111],
       [ 3.51583333],
       [ 6.72055556],
       [ 4.10555556],
       [ 3.48083333],
       [ 4.51833333],
       [ 4.5325    ],
       [ 3.68888889],
       [ 3.93888889],
       [ 6.01916667],
       [ 5.505     ],
       [ 2.95416667],
       [ 4.66527778],
       [ 4.245     ],
       [ 3.22222222],
       [ 3.91805556],
       [ 4.32361111],
       [ 3.98166667],
       [ 4.4075    ],
       [ 4.49055556],
       [ 6.29388889],
       [ 2.99138889],
       [ 4.48527778],
       [ 4.81277778],
       [ 3.44472222],
       [ 3.9675    ],
       [ 4.71333333],
       [ 3.78444444],
       [ 4.97027778],
       [ 4.94194444],
       [ 3.915     ],
       [ 4.97666667],
       [ 4.96305556],
       [ 3.90111111],
       [ 4.22388889],
       [ 4.245     ],
       [ 4

In [1453]:
np.sum(y_vec,axis=0)

array([ 3547.95222222])

In [1454]:
train_df.shape

(793, 6)

In [1455]:
def err_func_template(x,y):
    return lambda w:-2*((x.T).dot(y-x.dot(w)))

In [1456]:
err_func_grad=err_func_template(train_array,y_vec)

In [1458]:
def reg_template(x,y):
    return lambda w: -2*((x.T).dot(y-x.dot(w))) + np.sum(w)

In [1619]:
def grad_descent(fun,start,tol):
    i=1
    j=1
    w0=start
    w1=None
    while(True):
        i=i+1
        w1=w0-(1e-4/float(i))*fun(w0)
        if (math.sqrt(((w1-w0).T).dot(w1-w0))<tol):
            break
    return w1

In [1620]:
start_vec=(np.array([[0]*len(train_df.columns)])).T ################Double check when changing the features

In [1621]:
start_vec.shape

(6L, 1L)

In [1622]:
err_func_grad(start_vec)

array([[  -2045.21222222],
       [ -16382.79111111],
       [ -31513.01267253],
       [-291979.78611111],
       [  -9737.68202222],
       [  -7095.90444444]])

In [1629]:
w_vec=grad_descent(err_func_grad,start_vec,0.75)

In [1651]:
w_vec

array([[ 0.00511303],
       [ 0.04095698],
       [ 0.07878253],
       [ 0.72994947],
       [ 0.02434421],
       [ 0.01773976]])

In [1465]:
w_vec.shape

(6L, 1L)

In [ ]:
data_pivot['Time',2016]

In [1650]:
error=(((y_vec-train_array.dot(w_vec)).T).dot(y_vec-train_array.dot(w_vec)))[0][0]
error

570330.80758149293

In [1467]:
np.random.choice(train_df.index.tolist(),10)

array([1635, 1661,  668, 2230,  929, 2534,  607, 1815, 1886,  137], dtype=int64)

In [1468]:
#####This function gives a list of the different validation sets. Simply need to infer their complements to get training set
def rand_sel (frame,k):
    array=frame.index.tolist()
    random.shuffle(array)
    val_list=[]
    i=0
    while (True):
        if (len(array)-i*k>=k):
            val_list.append(array[i*k:(i+1)*k])
            i=i+1
        else:
            val_list.append(array[i*k:])
            break
    return val_list

In [1469]:
val_sets=rand_sel(train_df,10)

In [1470]:
len(val_sets)

80

In [1471]:
import copy

In [1472]:
def test_sets (frame,valid):
    array=[]
    work=frame.index.tolist()
    for lst in valid:
        temp=copy.deepcopy(work)
        for el in lst:
            temp.remove(el)
        array.append(temp)
    return array

In [1473]:
train_sets=test_sets(train_df,val_sets)

In [1474]:
k_fold_sets=(zip(val_sets,train_sets))

In [1475]:
k_fold_sets

[([801, 2555, 2143, 1702, 2247, 1820, 1136, 2945, 1168, 1531],
  [4,
   5,
   7,
   9,
   11,
   15,
   16,
   18,
   22,
   23,
   31,
   32,
   37,
   40,
   41,
   45,
   46,
   50,
   51,
   53,
   55,
   57,
   63,
   64,
   66,
   67,
   68,
   70,
   74,
   87,
   90,
   92,
   94,
   98,
   105,
   107,
   109,
   110,
   112,
   123,
   132,
   133,
   134,
   135,
   137,
   138,
   141,
   142,
   144,
   145,
   151,
   154,
   158,
   163,
   165,
   168,
   169,
   170,
   177,
   178,
   180,
   193,
   194,
   195,
   196,
   198,
   201,
   202,
   205,
   212,
   214,
   221,
   226,
   234,
   240,
   248,
   252,
   253,
   264,
   271,
   278,
   280,
   287,
   289,
   291,
   292,
   295,
   304,
   306,
   308,
   314,
   315,
   320,
   322,
   323,
   324,
   326,
   328,
   341,
   346,
   347,
   351,
   352,
   353,
   354,
   356,
   364,
   367,
   374,
   375,
   378,
   380,
   383,
   384,
   387,
   395,
   397,
   408,
   410,
   412,
   419,
   421,

In [1476]:
len(k_fold_sets)

80

In [1477]:
try_this=np.array(k_fold_sets[0][0])

In [1478]:
train_df.loc[try_this]

Sex  Num Marathons  Time of Last  Age Last  Sex Time  Dummy
Id                                                               
801   0.0            1.0      4.237778      40.0  0.000000    1.0
2555  1.0            1.0      4.094167      30.0  4.094167    1.0
2143  0.0            1.0      3.434167      35.0  0.000000    1.0
1702  1.0            2.0      5.097222      38.0  5.097222    1.0
2247  0.0            3.0      4.936111      35.0  0.000000    1.0
1820  0.0            1.0      4.117500      29.0  0.000000    1.0
1136  0.0            5.0      3.971667      45.0  0.000000    1.0
2945  0.0            2.0      5.066111      45.0  0.000000    1.0
1168  0.0            8.0      1.832500      42.0  0.000000    1.0
1531  0.0            2.0      4.055278      43.0  0.000000    1.0

In [1479]:
train_df.columns[0]

'Sex'

In [1643]:
def vali_err(frame,func,sets,year):
    err_sum=0.
    i=0
    for el in sets:
        frame_val=frame.loc[el[0]]
        frame_test=frame.loc[el[1]]
        array_val=frame_val.as_matrix()
        array_test=frame_test.as_matrix()
        start_point=(np.array([[0]*len(frame_test.columns)])).T
        y=get_y(frame_test,year) #this is the y vector
        w=grad_descent(func(array_test,y),start_point,0.75) #this is the w vector
        val=get_y(frame_val,year)
        err_sum=err_sum + (((val-array_val.dot(w)).T).dot(val-array_val.dot(w)))[0][0]
    return err_sum / float(len(sets))
        
        
        
        

In [1644]:
vali_err(train_df,err_func_template,k_fold_sets,2016)

7337.1234126510972

In [1641]:
#Now check for higher order models (i.e order 2 and 3)
def vali_err2(frame,func,sets,year):
    err_sum=0.
    new_frame=frame.copy(deep=True)
    new_frame['Age Last'+'2']=new_frame['Age Last']**2
    #for el in new_frame.columns:
        #new_frame[el+'ord2']=new_frame[el]**2
    for el in sets:
        new_frame_val=new_frame.loc[el[0]]
        new_frame_test=new_frame.loc[el[1]]
        array_val=new_frame_val.as_matrix()
        array_test=new_frame_test.as_matrix()
        start_point=(np.array([[0]*len(new_frame_test.columns)])).T
        y=get_y(new_frame_test,year) #this is the y vector
        w=grad_descent(func(array_test,y),start_point,0.75) #this is the w vector
        val=get_y(new_frame_val,year)
        err_sum=err_sum + (((val-array_val.dot(w)).T).dot(val-array_val.dot(w)))[0][0]
    return err_sum / float(len(sets))
        

In [1645]:
def vali_err3(frame,func,sets,year):
    err_sum=0.
    new_frame=frame.copy(deep=True)
    for el in new_frame.columns:
        new_frame[el+'ord2']=new_frame[el]**2
    new_frame2=frame.copy(deep=True)
    for el in new_frame2.columns:
        new_frame[el+'ord3']=new_frame[el]**3
    for el in sets:
        new_frame_val=new_frame.loc[el[0]]
        new_frame_test=new_frame.loc[el[1]]
        array_val=new_frame_val.as_matrix()
        array_test=new_frame_test.as_matrix()
        start_point=(np.array([[0]*len(new_frame_test.columns)])).T
        y=get_y(new_frame_test,year) #this is the y vector
        w=grad_descent(func(array_test,y),start_point,0.5) #this is the w vector
        val=get_y(new_frame_val,year)
        err_sum=err_sum + (((val-array_val.dot(w)).T).dot(val-array_val.dot(w)))[0][0]
    print err_sum / float(len(sets))
    return w

In [1646]:
vali_err2(train_df,err_func_template,k_fold_sets,2016)

21347014.71200721

In [1496]:
error=vali_err(train_df,err_func_template,k_fold_sets,2016)

In [1497]:
train_array_3.shape

(793L, 18L)

In [1498]:
error

204.8730781707537

In [1499]:
start_vec

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [1500]:
w_vect=grad_descent(err_func_template(train_array,y_vec),start_vec,1e-3)

In [1255]:
data_pivot = pd.pivot_table(marathon_data, index = ["Id"], columns = "Year", values = ["Rank","Age Category", "Time"], aggfunc= "first")

In [1327]:
test=create_frame(2016)

39.9580001831


In [1328]:
len(data_pivot)

30414

In [1329]:
test

Sex  Num Marathons  Years Since Last  Time of Last  Age Last  Sex Time  \
Id                                                                              
1      0.0              1                 1      4.250000      30.0  0.000000   
2      0.0              1                 1      5.095000      60.0  0.000000   
3      1.0              1                 1      5.076111      30.0  5.076111   
4      0.0              2                 1      5.225000      35.0  0.000000   
5      1.0              9                 1      5.476111      40.0  5.476111   
6      0.0              1                 1      4.706389      45.0  0.000000   
7      0.0              2                 1      3.600833      40.0  0.000000   
8      1.0              1                 1      3.987222      30.0  3.987222   
9      0.0              4                 1      5.496667      50.0  0.000000   
10     0.0              1                 1      4.770278      25.0  0.000000   
11     1.0              3                 1      4.863056      40.0  4.863056   
12     1.0              1                 1      4.011944      20.0  4.011944   
13     0.0              1                 1      2.975833      30.0  0.000000   
14     1.0              1                 1      3.997778      25.0  3.997778   
15     0.0              5                 1      5.146944      40.0  0.000000   
16     0.0              6                 1      4.060278      45.0  0.000000   
17     0.0              1                 1      3.976111      50.0  0.000000   
18     0.0              2                 1      6.818056      50.0  0.000000   
19     1.0              1                 1      5.383611      25.0  5.383611   
20     1.0              1                 1      3.074167      30.0  3.074167   
21     0.0              1                 1      4.041111      40.0  0.000000   
22     1.0              2                 1      4.162222      45.0  4.162222   
23     1.0              2                 1      4.433611      25.0  4.433611   
24     1.0              1                 1      3.746111      30.0  3.746111   
25     0.0              1                 1      3.915278      50.0  0.000000   
26     0.0              1                 1      4.568611      35.0  0.000000   
27     1.0              1                 1      4.285278      40.0  4.285278   
28     1.0              1                 1      5.324722      30.0  5.324722   
29     0.0              1                 1      5.275833      30.0  0.000000   
30     0.0              1                 1      5.528056      45.0  0.000000   
...    ...            ...               ...           ...       ...       ...   
30388  0.0              1                 2      5.117222      40.0  0.000000   
30389  0.0              1                 2      4.522500      35.0  0.000000   
30390  0.0              1                 2      4.076667      30.0  0.000000   
30391  1.0              1                 2      5.322778      25.0  5.322778   
30392  1.0              1                 2      6.232222      35.0  6.232222   
30393  1.0              1                 2      3.910833      40.0  3.910833   
30394  0.0              1                 2      5.395833      25.0  0.000000   
30395  0.0              1                 2      4.215278      45.0  0.000000   
30396  1.0              1                 2      4.885833      40.0  4.885833   
30397  0.0              1                 2      4.789167      35.0  0.000000   
30398  1.0              1                 2      6.748889      30.0  6.748889   
30399  1.0              1                 2      4.126389      35.0  4.126389   
30400  1.0              1                 2      2.659167      35.0  2.659167   
30401  0.0              1                 2      3.886389      40.0  0.000000   
30402  1.0              1                 2      3.448611      40.0  3.448611   
30403  1.0              1                 2      5.280556      40.0  5.280556   
30404  0.0              1             

In [1330]:
del test['Dummy']

In [1331]:
test_matrix=test.as_matrix()

In [1398]:
test_matrix.shape

(30414L, 6L)

In [1399]:
w_vect.shape

(6L, 1L)

In [1501]:
w_vect

array([[  2.04521222e-06],
       [  1.63827911e-05],
       [  3.15130127e-05],
       [  2.91979786e-04],
       [  9.73768202e-06],
       [  7.09590444e-06]])

In [1631]:
answer=test_matrix.dot(w_vec)

In [1632]:
answer

array([[ 3.95235089],
       [ 5.29948434],
       [ 4.65053228],
       ..., 
       [ 4.10171275],
       [ 3.86817415],
       [ 3.24575225]])

In [1633]:
test_dataframe=pd.DataFrame(answer)

In [1634]:
test_dataframe

0
0      3.952351
1      5.299484
2      4.650532
3      4.826730
4      5.520706
5      4.650655
6      3.762891
7      3.836382
8      5.472110
9      4.210406
10     4.816589
11     3.611424
12     3.022274
13     3.722553
14     5.014345
15     4.383811
16     4.239310
17     6.354743
18     4.758726
19     3.153700
20     4.043315
21     4.373347
22     4.089378
23     3.656106
24     4.194905
25     4.306642
26     4.302677
27     4.836416
28     4.701157
29     5.250430
...         ...
30384  4.907604
30385  4.351766
30386  3.904609
30387  4.792024
30388  5.715448
30389  4.101491
30390  4.745813
30391  4.370951
30392  4.830488
30393  4.546419
30394  5.980033
30395  4.140939
30396  3.043913
30397  4.009158
30398  3.755893
30399  5.125618
30400  4.022946
30401  3.446971
30402  4.229845
30403  4.177592
30404  4.592072
30405  4.327482
30406  4.243511
30407  5.719241
30408  4.582685
30409  4.059660
30410  3.741992
30411  4.101713
30412  3.868174
30413  3.245752

[30414 rows x 1 columns]

In [1663]:
marathon_data=pd.read_csv('c:\\Users\\willi\Downloads\\Project1_data.csv')
marathon_data=marathon_data.dropna()
marathon_data['Time']=pd.to_timedelta(marathon_data['Time'])
marathon_data.Time=marathon_data.Time.apply(lambda x: x.seconds /float(3600))

In [1664]:
data_pivot = pd.pivot_table(marathon_data, index = ["Id"], columns = "Year", values = ["Rank","Age Category", "Time"], aggfunc= "first")

In [1665]:
data_pivot=data_pivot =pd.pivot_table(marathon_data, index = ["Id"], columns = "Year", values = ["Rank","Age Category", "Time"], aggfunc= "first")

In [1666]:
test_new=create_frame(2016)

47.8980000019


In [1669]:
test_new

Sex  Num Marathons  Years Since Last  Time of Last  Age Last  Sex Time  \
Id                                                                              
1      0.0              1                 1      4.250000      30.0  0.000000   
2      0.0              1                 1      5.095000      60.0  0.000000   
3      1.0              1                 1      5.076111      30.0  5.076111   
4      0.0              2                 1      5.225000      35.0  0.000000   
5      1.0              9                 1      5.476111      40.0  5.476111   
6      0.0              1                 1      4.706389      45.0  0.000000   
7      0.0              2                 1      3.600833      40.0  0.000000   
8      1.0              1                 1      3.987222      30.0  3.987222   
9      0.0              4                 1      5.496667      50.0  0.000000   
10     0.0              1                 1      4.770278      25.0  0.000000   
11     1.0              3                 1      4.863056      40.0  4.863056   
12     1.0              1                 1      4.011944      20.0  4.011944   
13     0.0              1                 1      2.975833      30.0  0.000000   
14     1.0              1                 1      3.997778      25.0  3.997778   
15     0.0              5                 1      5.146944      40.0  0.000000   
16     0.0              6                 1      4.060278      45.0  0.000000   
17     0.0              1                 1      3.976111      50.0  0.000000   
18     0.0              2                 1      6.818056      50.0  0.000000   
19     1.0              1                 1      5.383611      25.0  5.383611   
20     1.0              1                 1      3.074167      30.0  3.074167   
21     0.0              1                 1      4.041111      40.0  0.000000   
22     1.0              2                 1      4.162222      45.0  4.162222   
23     1.0              2                 1      4.433611      25.0  4.433611   
24     1.0              1                 1      3.746111      30.0  3.746111   
25     0.0              1                 1      3.915278      50.0  0.000000   
26     0.0              1                 1      4.568611      35.0  0.000000   
27     1.0              1                 1      4.285278      40.0  4.285278   
28     1.0              1                 1      5.324722      30.0  5.324722   
29     0.0              1                 1      5.275833      30.0  0.000000   
30     0.0              1                 1      5.528056      45.0  0.000000   
...    ...            ...               ...           ...       ...       ...   
30388  0.0              1                 2      5.117222      40.0  0.000000   
30389  0.0              1                 2      4.522500      35.0  0.000000   
30390  0.0              1                 2      4.076667      30.0  0.000000   
30391  1.0              1                 2      5.322778      25.0  5.322778   
30392  1.0              1                 2      6.232222      35.0  6.232222   
30393  1.0              1                 2      3.910833      40.0  3.910833   
30394  0.0              1                 2      5.395833      25.0  0.000000   
30395  0.0              1                 2      4.215278      45.0  0.000000   
30396  1.0              1                 2      4.885833      40.0  4.885833   
30397  0.0              1                 2      4.789167      35.0  0.000000   
30398  1.0              1                 2      6.748889      30.0  6.748889   
30399  1.0              1                 2      4.126389      35.0  4.126389   
30400  1.0              1                 2      2.659167      35.0  2.659167   
30401  0.0              1                 2      3.886389      40.0  0.000000   
30402  1.0              1                 2      3.448611      40.0  3.448611   
30403  1.0              1                 2      5.280556      40.0  5.280556   
30404  0.0              1             

In [1673]:
del test_new['Dummy']

In [1674]:
test_new_matrix=test_new.as_matrix()

In [1675]:
answer2=test_new_matrix.dot(w_vec)

In [1676]:
test_new_frame=pd.DataFrame(answer2)

In [1677]:
test_new_frame

0
0      3.952351
1      5.299484
2      4.650532
3      4.826730
4      5.520706
5      4.650655
6      3.762891
7      3.836382
8      5.472110
9      4.210406
10     4.816589
11     3.611424
12     3.022274
13     3.722553
14     5.014345
15     4.383811
16     4.239310
17     6.354743
18     4.758726
19     3.153700
20     4.043315
21     4.373347
22     4.089378
23     3.656106
24     4.194905
25     4.306642
26     4.302677
27     4.836416
28     4.701157
29     5.250430
...         ...
30387  4.907604
30388  4.351766
30389  3.904609
30390  4.792024
30391  5.715448
30392  4.101491
30393  4.745813
30394  4.370951
30395  4.830488
30396  4.546419
30397  5.980033
30398  4.140939
30399  3.043913
30400  4.009158
30401  3.755893
30402  5.125618
30403  4.022946
30404  3.446971
30405  4.229845
30406  4.177592
30407  4.592072
30408  4.327482
30409  4.243511
30410  5.719241
30411  4.582685
30412  4.059660
30413  3.741992
30414  4.101713
30415  3.868174
30416  3.245752

[30417 rows x 1 columns]

In [1678]:
test_new_matrix.shape

(30417L, 6L)

In [1681]:
np.savetxt('c:\\Users\\willi\OneDrive\\Y2predictions.csv',answer2)